#!/usr/bin/env python3
"""
Pop Maker Studio — effect codegen
Reads effects/registry.json + shaders/*.glsl
Writes src/generated/*.h
Run from the repo root: python3 tools/codegen_effects.py
"""
import json, os, sys, math

ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG     = os.path.join(ROOT, "effects", "registry.json")
GEN_DIR = os.path.join(ROOT, "src", "generated")

def load_shader(path):
    full = os.path.join(ROOT, path)
    if not os.path.exists(full):
        print(f"  WARNING: shader not found: {path}", file=sys.stderr)
        return f"// MISSING: {path}"
    with open(full) as f:
        return f.read().rstrip()

def glsl_multiline(src, var):
    return f'static const char* {var} = R"glsl(\n{src}\n)glsl";'

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    banner = "// AUTO-GENERATED by tools/codegen_effects.py — do not edit manually\n"
    with open(path, "w") as f:
        f.write(banner + content)
    print(f"  wrote {os.path.relpath(path, ROOT)}")

def uniform_set_lines(p, eid, indent="            "):
    """Generate glUniform1f call for a param, applying power curve. Beat is baked into the accum."""
    uname = f'u_{p["name"]}'
    field = f'cfx.{eid}_{p["name"]}'
    curve = float(p.get("curve", 1.0))
    pmin  = float(p["min"])
    pmax  = float(p["max"])
    rng   = pmax - pmin

    if curve == 1.0 or rng <= 0.0:
        return [f'{indent}glUniform1f(glGetUniformLocation(p, "{uname}"), {field});']

    # Normalize stored value to [0,1], apply power curve, scale back to [min,max].
    lines = [
        f'{indent}{{',
        f'{indent}    float _n = ({field} - {pmin}f) / {rng}f;',
        f'{indent}    _n = _n < 0.0f ? 0.0f : (_n > 1.0f ? 1.0f : _n);',
        f'{indent}    glUniform1f(glGetUniformLocation(p, "{uname}"), {pmin}f + powf(_n, {curve}f) * {rng}f);',
        f'{indent}}}',
    ]
    return lines

def main():
    with open(REG) as f:
        reg = json.load(f)
    effects = reg["effects"]
    print(f"codegen: {len(effects)} effects")

    # ── fx_enum_entries.h ─────────────────────────────────────────────────────
    lines = []
    for e in effects:
        lines.append(f'    {e["enum"]},   // {e["label"]}')
    write(os.path.join(GEN_DIR, "fx_enum_entries.h"), "\n".join(lines) + "\n")

    # ── fx_accum_fields.h ─────────────────────────────────────────────────────
    # Amount is a system field alongside the params.
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'    bool  {eid}_on = false;')
        lines.append(f'    float {eid}_amount = 0.0f;')
        for p in e["params"]:
            lines.append(f'    float {eid}_{p["name"]} = {float(p["min"])}f;')
    write(os.path.join(GEN_DIR, "fx_accum_fields.h"), "\n".join(lines) + "\n")

    # ── fx_clip_fields.h ──────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'    float fx_{eid}_amount = 1.0f;')
        for p in e["params"]:
            lines.append(f'    float fx_{eid}_{p["name"]} = {float(p["default"])}f;')
            lines.append(f'    float fx_{eid}_{p["name"]}_beat = 0.0f;')  # beat sync intensity dial (0=off)
    write(os.path.join(GEN_DIR, "fx_clip_fields.h"), "\n".join(lines) + "\n")

    # ── fx_collect_cases.h ────────────────────────────────────────────────────
    # Note: _cl_beat_pulse must be computed in the calling scope before the switch.
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'        case FXType::{e["enum"]}:')
        lines.append(f'            acc.{eid}_on = true;')
        lines.append(f'            acc.any_gen_fx = true;')
        lines.append(f'            acc.{eid}_amount = fmaxf(acc.{eid}_amount, cl.fx_{eid}_amount);')
        for p in e["params"]:
            pmin = float(p["min"])
            pmax = float(p["max"])
            lines.append(f'            {{')
            lines.append(f'                float _bi = cl.fx_{eid}_{p["name"]}_beat;')
            lines.append(f'                float _bv = cl.fx_{eid}_{p["name"]};')
            lines.append(f'                acc.{eid}_{p["name"]} = fmaxf(acc.{eid}_{p["name"]}, (_bi > 0.001f) ? ({pmin}f + ({pmax}f - {pmin}f) * _bi * _cl_beat_pulse) : _bv);')
            lines.append(f'            }}')
        lines.append(f'            break;')
    write(os.path.join(GEN_DIR, "fx_collect_cases.h"), "\n".join(lines) + "\n")

    # ── fx_shader_strings.h ───────────────────────────────────────────────────
    lines = []
    for e in effects:
        src = load_shader(e["shader"])
        var = f'k_{e["id"]}_frag'
        lines.append(glsl_multiline(src, var))
        lines.append("")
    write(os.path.join(GEN_DIR, "fx_shader_strings.h"), "\n".join(lines))

    # ── fx_shader_init.h ──────────────────────────────────────────────────────
    lines = ["void fx_generated_init() {"]
    for e in effects:
        lines.append(f'    g_gen_progs[(int)FXType::{e["enum"]}] = link_prog(k_{e["id"]}_frag);')
    lines.append("}")
    write(os.path.join(GEN_DIR, "fx_shader_init.h"), "\n".join(lines) + "\n")

    # ── fx_shader_apply.h ─────────────────────────────────────────────────────
    # Guard: effect_on && amount > 0.01.
    # Pipeline: save pre_tex, run effect, then blend if amount < 1.
    # Power curve applied per-param when setting uniforms.
    lines = []
    for e in effects:
        eid = e["id"]
        cond = f'cfx.{eid}_on && cfx.{eid}_amount > 0.01f'
        lines.append(f'    if ({cond}) {{')
        lines.append(f'        GLuint p = g_gen_progs[(int)FXType::{e["enum"]}];')
        lines.append(f'        if (p) {{')
        lines.append(f'            GLuint pre_tex = cur;')
        lines.append(f'            glUseProgram(p);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_tex_w"), (float)w);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_tex_h"), (float)h);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_time"),  t);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_strength"), cfx.{eid}_amount);')
        for p in e["params"]:
            if p.get("hidden"): continue
            lines.extend(uniform_set_lines(p, eid))
        lines.append(f'            run1(p);')
        lines.append(f'            if (cfx.{eid}_amount < 0.999f) {{')
        lines.append(f'                draw_blend_pass(pre_tex, cur, cfx.{eid}_amount, g_pp.fbo[pslot], w, h);')
        lines.append(f'                cur = g_pp.tex[pslot];')
        lines.append(f'                pslot ^= 1;')
        lines.append(f'            }}')
        lines.append(f'        }}')
        lines.append(f'    }}')
        lines.append('')
    write(os.path.join(GEN_DIR, "fx_shader_apply.h"), "\n".join(lines))

    # ── fx_project_write.h ────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'    w.pod(c.fx_{eid}_amount);')
        for p in e["params"]:
            lines.append(f'    w.pod(c.fx_{eid}_{p["name"]});')
            lines.append(f'    w.pod(c.fx_{eid}_{p["name"]}_beat);')
    write(os.path.join(GEN_DIR, "fx_project_write.h"), "\n".join(lines) + "\n")

    # ── fx_project_read.h ─────────────────────────────────────────────────────
    pv = reg["project_version"]
    lines = [f'    if (version >= {pv}u) {{']
    for e in effects:
        eid = e["id"]
        lines.append(f'        c.fx_{eid}_amount = r.pod<float>();')
        for p in e["params"]:
            lines.append(f'        c.fx_{eid}_{p["name"]} = r.pod<float>();')
            lines.append(f'        c.fx_{eid}_{p["name"]}_beat = r.pod<float>();')
    lines.append('    }')
    write(os.path.join(GEN_DIR, "fx_project_read.h"), "\n".join(lines) + "\n")

    # ── fx_ui_inspector.h ─────────────────────────────────────────────────────
    # Amount slider first (system), then effect params with beat sync buttons.
    lines = []
    for e in effects:
        eid = e["id"]
        elabel = e["label"]
        lines.append(f'        case FXType::{e["enum"]}:')
        lines.append(f'            ui_label("Amount");')
        lines.append(f'            ImGui::SetNextItemWidth(sw);')
        lines.append(f'            ImGui::SliderFloat("##gen_{eid}_amount", &clip.fx_{eid}_amount, 0.0f, 1.0f, "%.2f");')
        lines.append(f'            if (ImGui::IsItemDeactivatedAfterEdit()) history_push(state, "{elabel}: Amount");')
        for i, p in enumerate(e["params"]):
            if p.get("hidden"): continue
            pname = p["name"]
            plabel = p["label"]
            lines.append('            ImGui::Dummy({0.f, 4.f});')
            lines.append(f'            ui_label("{plabel}");')
            lines.append(f'            {{')
            lines.append(f'                bool _bon = clip.fx_{eid}_{pname}_beat > 0.001f;')
            lines.append(f'                if (_bon) ImGui::BeginDisabled();')
            lines.append(f'                ImGui::SetNextItemWidth(sw - 26.f);')
            lines.append(f'                ImGui::SliderFloat("##gen_{eid}_{pname}", &clip.fx_{eid}_{pname}, {float(p["min"])}f, {float(p["max"])}f, "{p["fmt"]}");')
            lines.append(f'                if (ImGui::IsItemDeactivatedAfterEdit()) history_push(state, "{elabel}: {plabel}");')
            lines.append(f'                if (_bon) ImGui::EndDisabled();')
            lines.append(f'                ImGui::SameLine(0.f, 4.f);')
            lines.append(f'                ImGui::PushStyleColor(ImGuiCol_Text, _bon ? IM_COL32(255,200,50,255) : IM_COL32(120,120,140,200));')
            lines.append(f'                if (ImGui::SmallButton("B##bt_{eid}_{pname}")) {{')
            lines.append(f'                    clip.fx_{eid}_{pname}_beat = _bon ? 0.f : 0.5f;')
            lines.append(f'                    history_push(state, "{elabel}: Beat Sync");')
            lines.append(f'                }}')
            lines.append(f'                ImGui::PopStyleColor();')
            lines.append(f'                if (_bon) {{')
            lines.append(f'                    ImGui::SetNextItemWidth(sw);')
            lines.append(f'                    ImGui::SliderFloat("##bi_{eid}_{pname}", &clip.fx_{eid}_{pname}_beat, 0.0f, 1.0f, "beat %.2f");')
            lines.append(f'                    if (ImGui::IsItemDeactivatedAfterEdit()) history_push(state, "{elabel}: Beat Intensity");')
            lines.append(f'                }}')
            lines.append(f'            }}')
        lines.append('            break;')
        lines.append('')
    write(os.path.join(GEN_DIR, "fx_ui_inspector.h"), "\n".join(lines))

    # ── fx_ui_meta.h — color, abbrev, label for switch helpers ───────────────
    color_cases, abbrev_cases, label_cases, picker_entries = [], [], [], []
    for e in effects:
        col = e["color"]
        color_cases.append(f'        case FXType::{e["enum"]}: return IM_COL32({col[0]},{col[1]},{col[2]},{col[3]});')
        abbrev_cases.append(f'        case FXType::{e["enum"]}: return "{e["abbrev"]}";')
        label_cases.append(f'        case FXType::{e["enum"]}: return "{e["label"]}";')
        picker_entries.append(f'        {{FXType::{e["enum"]}, "{e["label"]}", "{e["description"]}", IM_COL32({col[0]},{col[1]},{col[2]},{col[3]})}},')

    write(os.path.join(GEN_DIR, "fx_ui_color.h"),   "\n".join(color_cases)   + "\n")
    write(os.path.join(GEN_DIR, "fx_ui_abbrev.h"),  "\n".join(abbrev_cases)  + "\n")
    write(os.path.join(GEN_DIR, "fx_ui_label.h"),   "\n".join(label_cases)   + "\n")
    write(os.path.join(GEN_DIR, "fx_ui_picker.h"),  "\n".join(picker_entries) + "\n")

    # ── fx_preview_defaults.h ─────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'        case FXType::{e["enum"]}:')
        lines.append(f'            cfx.{eid}_on = true;')
        lines.append(f'            cfx.{eid}_amount = 1.0f;')
        for p in e["params"]:
            lines.append(f'            cfx.{eid}_{p["name"]} = {float(p["default"])}f;')
        lines.append(f'            break;')
    write(os.path.join(GEN_DIR, "fx_preview_defaults.h"), "\n".join(lines) + "\n")

    # ── fx_type_list.h ────────────────────────────────────────────────────────
    entries = [f'    FXType::{e["enum"]},' for e in effects]
    content = "static const FXType k_gen_fx_types[] = {\n"
    content += "\n".join(entries) + "\n"
    content += f"}};\nstatic const int k_gen_fx_count = {len(effects)};\n"
    write(os.path.join(GEN_DIR, "fx_type_list.h"), content)

    # ── fx_gen_names.h ────────────────────────────────────────────────────────
    lines = [f'    "{e["id"]}",' for e in effects]
    write(os.path.join(GEN_DIR, "fx_gen_names.h"), "\n".join(lines) + "\n")

    # ── fx_attached_accum.h ───────────────────────────────────────────────────
    # Populates CreativeFXAccum from a single AttachedFX (type + amount + params vector).
    # Params vector contains non-hidden params in registry order.
    lines = ["static void fx_accum_from_attached(CreativeFXAccum& acc, FXType type, float amount, const std::vector<float>& pv) {",
             "    switch (type) {"]
    for e in effects:
        eid = e["id"]
        visible_params = [p for p in e["params"] if not p.get("hidden")]
        lines.append(f'        case FXType::{e["enum"]}:')
        lines.append(f'            acc.{eid}_on = true;')
        lines.append(f'            acc.{eid}_amount = fmaxf(acc.{eid}_amount, amount);')
        for i, p in enumerate(visible_params):
            lines.append(f'            if ((int)pv.size() > {i}) acc.{eid}_{p["name"]} = fmaxf(acc.{eid}_{p["name"]}, pv[{i}]);')
        lines.append(f'            acc.any_gen_fx = true;')
        lines.append(f'            break;')
    lines.append("        default: break;")
    lines.append("    }")
    lines.append("}")
    write(os.path.join(GEN_DIR, "fx_attached_accum.h"), "\n".join(lines) + "\n")

    # ── fx_attached_defaults.h ────────────────────────────────────────────────
    # Returns default param values (non-hidden) for a given FXType.
    lines = ["static std::vector<float> fx_attached_defaults(FXType type) {",
             "    switch (type) {"]
    for e in effects:
        visible_params = [p for p in e["params"] if not p.get("hidden")]
        defaults = ", ".join(f"{float(p['default'])}f" for p in visible_params)
        lines.append(f'        case FXType::{e["enum"]}: return {{{defaults}}};')
    lines.append("        default: return {};")
    lines.append("    }")
    lines.append("}")
    write(os.path.join(GEN_DIR, "fx_attached_defaults.h"), "\n".join(lines) + "\n")

    # ── fx_attached_ui.h ──────────────────────────────────────────────────────
    # Inspector UI for a single AttachedFX — operates on afx.amount and afx.params[i].
    lines = ["static void fx_attached_inspector(AttachedFX& afx, float sw, AppState& state, Clip& clip) {",
             "    (void)clip;",
             "    switch (afx.type) {"]
    for e in effects:
        eid = e["id"]
        visible_params = [p for p in e["params"] if not p.get("hidden")]
        n = len(visible_params)
        lines.append(f'        case FXType::{e["enum"]}: {{')
        lines.append(f'            if ((int)afx.params.size() < {n}) afx.params.resize({n}, 0.f);')
        lines.append(f'            ui_label("Amount");')
        lines.append(f'            ImGui::SetNextItemWidth(sw);')
        lines.append(f'            ImGui::SliderFloat("##afx_{eid}_amount", &afx.amount, 0.0f, 1.0f, "%.2f");')
        lines.append(f'            if (ImGui::IsItemDeactivatedAfterEdit()) history_push(state, "{e["label"]}: Amount");')
        for i, p in enumerate(visible_params):
            lines.append(f'            ImGui::Dummy({{0.f, 4.f}});')
            lines.append(f'            ui_label("{p["label"]}");')
            lines.append(f'            ImGui::SetNextItemWidth(sw);')
            lines.append(f'            ImGui::SliderFloat("##afx_{eid}_{p["name"]}", &afx.params[{i}], {float(p["min"])}f, {float(p["max"])}f, "{p["fmt"]}");')
            lines.append(f'            if (ImGui::IsItemDeactivatedAfterEdit()) history_push(state, "{e["label"]}: {p["label"]}");')
        lines.append(f'            break;')
        lines.append(f'        }}')
    lines.append("        default: break;")
    lines.append("    }")
    lines.append("}")
    write(os.path.join(GEN_DIR, "fx_attached_ui.h"), "\n".join(lines) + "\n")

    print(f"done — {len(effects)} effects, project version {reg['project_version']}")

if __name__ == "__main__":
    main()
