#!/usr/bin/env python3
"""
Pop Maker Studio — effect codegen
Reads effects/registry.json + shaders/*.glsl
Writes src/generated/*.h
Run from the repo root: python3 tools/codegen_effects.py
"""
import json, os, sys, textwrap

ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG     = os.path.join(ROOT, "effects", "registry.json")
GEN_DIR = os.path.join(ROOT, "src", "generated")

def load_shader(path):
    full = os.path.join(ROOT, path)
    if not os.path.exists(full):
        print(f"  WARNING: shader not found: {path}", file=sys.stderr)
        return f"// MISSING: {path}"
    with open(full) as f:
        return f.read().rstrip()

def c_string(src, var):
    escaped = src.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n\"\n\"")
    return f'static const char* {var} = "{escaped}";'

def glsl_multiline(src, var):
    return f'static const char* {var} = R"glsl(\n{src}\n)glsl";'

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    banner = "// AUTO-GENERATED by tools/codegen_effects.py — do not edit manually\n"
    with open(path, "w") as f:
        f.write(banner + content)
    print(f"  wrote {os.path.relpath(path, ROOT)}")

def main():
    with open(REG) as f:
        reg = json.load(f)
    effects = reg["effects"]
    print(f"codegen: {len(effects)} effects")

    # ── fx_enum_entries.h ─────────────────────────────────────────────────────
    lines = []
    for e in effects:
        lines.append(f'    {e["enum"]},   // {e["label"]}')
    write(os.path.join(GEN_DIR, "fx_enum_entries.h"), "\n".join(lines) + "\n")

    # ── fx_accum_fields.h ─────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'    bool  {eid}_on = false;')
        for p in e["params"]:
            lines.append(f'    float {eid}_{p["name"]} = {float(p["default"])}f;')
    write(os.path.join(GEN_DIR, "fx_accum_fields.h"), "\n".join(lines) + "\n")

    # ── fx_clip_fields.h ──────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        for p in e["params"]:
            lines.append(f'    float fx_{eid}_{p["name"]} = {float(p["default"])}f;')
    write(os.path.join(GEN_DIR, "fx_clip_fields.h"), "\n".join(lines) + "\n")

    # ── fx_collect_cases.h ────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'        case FXType::{e["enum"]}:')
        lines.append(f'            acc.{eid}_on = true;')
        lines.append(f'            acc.any_gen_fx = true;')
        for p in e["params"]:
            lines.append(f'            acc.{eid}_{p["name"]} = fmaxf(acc.{eid}_{p["name"]}, cl.fx_{eid}_{p["name"]});')
        lines.append(f'            break;')
    write(os.path.join(GEN_DIR, "fx_collect_cases.h"), "\n".join(lines) + "\n")

    # ── fx_shader_strings.h ───────────────────────────────────────────────────
    lines = []
    for e in effects:
        src = load_shader(e["shader"])
        var = f'k_{e["id"]}_frag'
        lines.append(glsl_multiline(src, var))
        lines.append("")
    write(os.path.join(GEN_DIR, "fx_shader_strings.h"), "\n".join(lines))

    # ── fx_shader_init.h ──────────────────────────────────────────────────────
    lines = ["void fx_generated_init() {"]
    for e in effects:
        lines.append(f'    g_gen_progs[(int)FXType::{e["enum"]}] = link_prog(k_{e["id"]}_frag);')
    lines.append("}")
    write(os.path.join(GEN_DIR, "fx_shader_init.h"), "\n".join(lines) + "\n")

    # ── fx_shader_apply.h ─────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        cond_parts = [f'cfx.{eid}_on']
        # Only add secondary guard when there's a dedicated 'strength' param (min=0)
        for p in e["params"]:
            if p.get("hidden"): continue
            if p["name"] == "strength" and float(p["min"]) == 0.0:
                cond_parts.append(f'cfx.{eid}_strength > 0.01f')
                break
        cond = " && ".join(cond_parts)
        lines.append(f'    if ({cond}) {{')
        lines.append(f'        GLuint p = g_gen_progs[(int)FXType::{e["enum"]}];')
        lines.append(f'        if (p) {{')
        lines.append(f'            glUseProgram(p);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_tex_w"), (float)w);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_tex_h"), (float)h);')
        lines.append(f'            glUniform1f(glGetUniformLocation(p, "u_time"),  t);')
        for p in e["params"]:
            uname = f'u_{p["name"]}'
            lines.append(f'            glUniform1f(glGetUniformLocation(p, "{uname}"), cfx.{eid}_{p["name"]});')
        lines.append(f'            run1(p);')
        lines.append(f'        }}')
        lines.append(f'    }}')
        lines.append('')
    write(os.path.join(GEN_DIR, "fx_shader_apply.h"), "\n".join(lines))

    # ── fx_project_write.h ────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        for p in e["params"]:
            lines.append(f'    w.pod(c.fx_{eid}_{p["name"]});')
    write(os.path.join(GEN_DIR, "fx_project_write.h"), "\n".join(lines) + "\n")

    # ── fx_project_read.h ─────────────────────────────────────────────────────
    lines = [f'    if (version >= {reg["project_version"]}u) {{']
    for e in effects:
        eid = e["id"]
        for p in e["params"]:
            lines.append(f'        c.fx_{eid}_{p["name"]} = r.pod<float>();')
    lines.append('    }')
    write(os.path.join(GEN_DIR, "fx_project_read.h"), "\n".join(lines) + "\n")

    # ── fx_ui_inspector.h ─────────────────────────────────────────────────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'        case FXType::{e["enum"]}:')
        for i, p in enumerate(e["params"]):
            if i > 0:
                lines.append('            ImGui::Dummy({0.f, 4.f});')
            lines.append(f'            ui_label("{p["label"]}");')
            lines.append(f'            ImGui::SetNextItemWidth(sw);')
            lines.append(f'            ImGui::SliderFloat("##gen_{eid}_{p["name"]}", &clip.fx_{eid}_{p["name"]}, {float(p["min"])}f, {float(p["max"])}f, "{p["fmt"]}");')
            lines.append(f'            if (ImGui::IsItemDeactivatedAfterEdit()) history_push(state, "{e["label"]}: {p["label"]}");')
        lines.append('            break;')
        lines.append('')
    write(os.path.join(GEN_DIR, "fx_ui_inspector.h"), "\n".join(lines))

    # ── fx_ui_meta.h — color, abbrev, label, name for switch helpers ──────────
    color_cases, abbrev_cases, label_cases, name_cases, picker_entries = [], [], [], [], []
    for e in effects:
        col = e["color"]
        color_cases.append(f'        case FXType::{e["enum"]}: return IM_COL32({col[0]},{col[1]},{col[2]},{col[3]});')
        abbrev_cases.append(f'        case FXType::{e["enum"]}: return "{e["abbrev"]}";')
        label_cases.append(f'        case FXType::{e["enum"]}: return "{e["label"]}";')
        name_cases.append(f'        case FXType::{e["enum"]}: return "{e["label"]}";')
        picker_entries.append(f'        {{FXType::{e["enum"]}, "{e["label"]}", "{e["description"]}", IM_COL32({col[0]},{col[1]},{col[2]},{col[3]})}},')

    write(os.path.join(GEN_DIR, "fx_ui_color.h"),   "\n".join(color_cases)   + "\n")
    write(os.path.join(GEN_DIR, "fx_ui_abbrev.h"),  "\n".join(abbrev_cases)  + "\n")
    write(os.path.join(GEN_DIR, "fx_ui_label.h"),   "\n".join(label_cases)   + "\n")
    write(os.path.join(GEN_DIR, "fx_ui_picker.h"),  "\n".join(picker_entries) + "\n")

    # ── fx_preview_defaults.h — switch cases for fx_preview_gen_effect ──────────
    lines = []
    for e in effects:
        eid = e["id"]
        lines.append(f'        case FXType::{e["enum"]}:')
        lines.append(f'            cfx.{eid}_on = true;')
        for p in e["params"]:
            lines.append(f'            cfx.{eid}_{p["name"]} = {float(p["default"])}f;')
        lines.append(f'            break;')
    write(os.path.join(GEN_DIR, "fx_preview_defaults.h"), "\n".join(lines) + "\n")

    # ── fx_type_list.h — array for --dump-fx-previews ────────────────────────
    entries = [f'    FXType::{e["enum"]},' for e in effects]
    content = "static const FXType k_gen_fx_types[] = {\n"
    content += "\n".join(entries) + "\n"
    content += f"}};\nstatic const int k_gen_fx_count = {len(effects)};\n"
    write(os.path.join(GEN_DIR, "fx_type_list.h"), content)

    # ── fx_gen_names.h — effect id strings for --dump-fx-previews filenames ──
    lines = [f'    "{e["id"]}",' for e in effects]
    write(os.path.join(GEN_DIR, "fx_gen_names.h"), "\n".join(lines) + "\n")

    print(f"done — {len(effects)} effects, project version {reg['project_version']}")

if __name__ == "__main__":
    main()
