#!/usr/bin/env python3
"""Bake the body-FX card preview source: a small 9:16 portrait + its U2Net body
mask, emitted as a committed C header (src/generated/body_fx_preview.h).

The body-FX shaders sample u_mask, so the preview thumbnails need a mask of the
source image — unlike the gen-FX previews, which don't. Run once when the source
image changes:  python3 tools/gen_body_fx_preview.py [src.jpg]
"""
import sys, numpy as np
from PIL import Image
import onnxruntime as ort

SRC   = sys.argv[1] if len(sys.argv) > 1 else \
        "/home/alexis/Downloads/pexels-nguy-n-ti-n-th-nh-2150376175-37934548.jpg"
MODEL = "build/models/u2netp_human_seg.onnx"
OUT_H = "src/generated/body_fx_preview.h"
PW, PH = 144, 256          # preview dims (9:16)

MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

# Load + center-crop to 9:16
img = Image.open(SRC).convert("RGB")
w, h = img.size
tar = PW / PH
if w / h > tar:                       # too wide -> crop sides
    nw = int(round(h * tar)); x0 = (w - nw) // 2
    img = img.crop((x0, 0, x0 + nw, h))
else:                                  # too tall -> crop top/bottom
    nh = int(round(w / tar)); y0 = (h - nh) // 2
    img = img.crop((0, y0, w, y0 + nh))

prev_rgb = np.asarray(img.resize((PW, PH), Image.LANCZOS), dtype=np.uint8)   # (PH,PW,3)

# U2Net body mask: 320x320, normalize, NCHW
u   = np.asarray(img.resize((320, 320), Image.LANCZOS), dtype=np.float32) / 255.0
chw = np.transpose((u - MEAN) / STD, (2, 0, 1))[None].astype(np.float32)     # (1,3,320,320)
sess = ort.InferenceSession(MODEL, providers=["CPUExecutionProvider"])
out  = sess.run(None, {sess.get_inputs()[0].name: chw})[0]                   # (1,1,320,320)
m    = out[0, 0]
m    = (m - m.min()) / (m.max() - m.min() + 1e-6)
mask_arr = np.asarray(Image.fromarray((m * 255).astype(np.uint8)).resize((PW, PH), Image.LANCZOS),
                      dtype=np.uint8)                                        # (PH,PW)

# Debug: composite over checkerboard so I can eyeball the mask
chk = np.zeros((PH, PW, 3), np.uint8)
for y in range(PH):
    for x in range(PW):
        chk[y, x] = 160 if ((x >> 4) ^ (y >> 4)) & 1 else 96
a = (mask_arr[..., None] / 255.0)
comp = (prev_rgb * a + chk * (1 - a)).astype(np.uint8)
Image.fromarray(comp).save("/tmp/body_fx_preview_check.png")

def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"static const uint8_t {name}[{len(flat)}] = {{\n")
    for i in range(0, len(flat), 24):
        f.write(",".join(str(int(v)) for v in flat[i:i+24]) + ",\n")
    f.write("};\n")

with open(OUT_H, "w") as f:
    f.write("// Generated by tools/gen_body_fx_preview.py — DO NOT EDIT.\n")
    f.write("// Body-FX card preview source: a 9:16 portrait + its U2Net body mask,\n")
    f.write("// fed through body_fx_apply() to render the per-effect card thumbnails.\n")
    f.write("#pragma once\n#include <cstdint>\n")
    f.write(f"static const int body_fx_preview_w = {PW};\n")
    f.write(f"static const int body_fx_preview_h = {PH};\n")
    emit(f, "body_fx_preview_rgb",  prev_rgb)
    emit(f, "body_fx_preview_mask", mask_arr)

print(f"wrote {OUT_H}  {PW}x{PH}  rgb={prev_rgb.size}  mask={mask_arr.size}  "
      f"(check /tmp/body_fx_preview_check.png)")
