#!/usr/bin/env python3
"""Generate src/generated/agent_tools.h for the in-app agent harness.

Sources of truth (see AGENT_HARNESS.md):
  - mcp_server/server.py --dump-tools   → names, descriptions, input schemas
  - src/ipc_server.cpp                  → which methods the socket actually serves

A tool is available to the in-app harness iff its name is a real IPC method;
tools implemented inside server.py (activity scans, contact sheets, transcript
search orchestration, ...) are tagged "ipc": false and omitted from the
model's tool list at runtime. The intersection is computed here so neither
side hand-maintains a list that can rot.

Run from the repo root after changing tool definitions in server.py:
    python3 tools/gen_agent_tools.py
The output header is committed, same policy as the fx_* generated headers.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVER = ROOT / "mcp_server" / "server.py"
IPC = ROOT / "src" / "ipc_server.cpp"
OUT = ROOT / "src" / "generated" / "agent_tools.h"


def main():
    dump = subprocess.run(
        [sys.executable, str(SERVER), "--dump-tools"],
        capture_output=True, text=True, check=True,
    )
    tools = json.loads(dump.stdout)

    ipc_src = IPC.read_text()
    methods = set(re.findall(r'method == "([a-zA-Z0-9_]+)"', ipc_src))
    if not methods:
        raise SystemExit("no IPC methods found in ipc_server.cpp — wrong path?")

    for t in tools:
        t["ipc"] = t["name"] in methods

    n_ipc = sum(t["ipc"] for t in tools)
    payload = json.dumps(tools, ensure_ascii=False, separators=(",", ":"))
    if ")PMSTOOLS" in payload:
        raise SystemExit("raw-string delimiter collision — change the delimiter")

    header = (
        "// generated by tools/gen_agent_tools.py — DO NOT EDIT.\n"
        "// Source of truth: mcp_server/server.py (--dump-tools) intersected with\n"
        "// the IPC methods in src/ipc_server.cpp. Regenerate after changing tool\n"
        "// definitions:  python3 tools/gen_agent_tools.py\n"
        f"// {len(tools)} tools, {n_ipc} servable over IPC by the in-app harness.\n"
        "#pragma once\n\n"
        "// JSON array of {name, description, inputSchema, ipc}.\n"
        "static const char* AGENT_TOOLS_JSON = R\"PMSTOOLS(" + payload + ")PMSTOOLS\";\n"
    )
    OUT.write_text(header)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(tools)} tools, {n_ipc} ipc-servable")
    skipped = sorted(t["name"] for t in tools if not t["ipc"])
    print("python-only (omitted from in-app toolset):", ", ".join(skipped))


if __name__ == "__main__":
    main()
