#!/usr/bin/env python3
"""Generate src/generated/face_uv_mesh.h from MediaPipe's canonical face model
(468 verts + UVs + 898 tris; Apache 2.0). UVs are stored image-style
(v flipped) so the shader samples the makeup PNG directly."""
import os
here = os.path.dirname(os.path.abspath(__file__))
tris = []
vt_raw = []
v2vt = {}
for line in open(os.path.join(here, "canonical_face_model.obj")):
    p = line.split()
    if not p: continue
    if p[0] == "vt": vt_raw.append((float(p[1]), float(p[2])))
    elif p[0] == "f":
        vs = []
        for x in p[1:4]:
            vi, ti = x.split("/")[:2]
            vi, ti = int(vi) - 1, int(ti) - 1
            v2vt[vi] = ti          # v→vt mapping lives in the face elements
            vs.append(vi)
        tris.append(vs)
assert len(vt_raw) == 468 and len(tris) == 898 and len(v2vt) == 468
vt = [vt_raw[v2vt[i]] for i in range(468)]
out = ["// GENERATED by tools/gen_face_uv.py from MediaPipe canonical_face_model.obj",
       "// (Apache 2.0). UV per landmark 0..467, image-space (v flipped); 898 tris.",
       "#pragma once",
       f"static const int FACE_UV_NPTS = {len(vt)};",
       f"static const int FACE_UV_NTRI = {len(tris)};",
       "static const float k_face_uv[468][2] = {"]
for u, v in vt: out.append(f"    {{{u:.6f}f, {1.0 - v:.6f}f}},")
out.append("};")
out.append("static const unsigned short k_face_tris[898][3] = {")
for a, b, c in tris: out.append(f"    {{{a}, {b}, {c}}},")
out.append("};")
open(os.path.join(here, "..", "src", "generated", "face_uv_mesh.h"), "w").write("\n".join(out) + "\n")
print("wrote face_uv_mesh.h")
