#!/usr/bin/env python3
"""Generate src/generated/agent_tools.h for the in-app agent harness.

Sources of truth (see AGENT_HARNESS.md):
  - mcp_server/server.py --dump-tools   → names, descriptions, input schemas
  - src/ipc_server.cpp                  → which methods the socket actually serves

Each tool is tagged "ipc": true when its name is a real IPC method (the
harness dispatches those straight to the editor socket) or "ipc": false when
it is implemented inside server.py (activity scans, contact sheets,
transcript search orchestration, ...) — those route through the harness's
server.py MCP stdio bridge. The flag is computed here so neither side
hand-maintains a list that can rot.

Run from the repo root after changing tool definitions in server.py:
    python3 tools/gen_agent_tools.py
The output header is committed, same policy as the fx_* generated headers.
Pass --check to verify the committed header is fresh without rewriting it
(exit 1 if stale) — for CI or a pre-commit hook.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVER = ROOT / "mcp_server" / "server.py"
IPC = ROOT / "src" / "ipc_server.cpp"
OUT = ROOT / "src" / "generated" / "agent_tools.h"


def main():
    dump = subprocess.run(
        [sys.executable, str(SERVER), "--dump-tools"],
        capture_output=True, text=True, check=True,
    )
    tools = json.loads(dump.stdout)

    ipc_src = IPC.read_text()
    methods = set(re.findall(r'method == "([a-zA-Z0-9_]+)"', ipc_src))
    if not methods:
        raise SystemExit("no IPC methods found in ipc_server.cpp — wrong path?")

    for t in tools:
        t["ipc"] = t["name"] in methods

    n_ipc = sum(t["ipc"] for t in tools)
    payload = json.dumps(tools, ensure_ascii=False, separators=(",", ":"))
    if ")PMSTOOLS" in payload:
        raise SystemExit("raw-string delimiter collision — change the delimiter")

    header = (
        "// generated by tools/gen_agent_tools.py — DO NOT EDIT.\n"
        "// Source of truth: mcp_server/server.py (--dump-tools) intersected with\n"
        "// the IPC methods in src/ipc_server.cpp. Regenerate after changing tool\n"
        "// definitions:  python3 tools/gen_agent_tools.py\n"
        f"// {len(tools)} tools: {n_ipc} dispatched straight to the IPC socket,\n"
        "// the rest through the harness's server.py MCP stdio bridge.\n"
        "#pragma once\n\n"
        "// JSON array of {name, description, inputSchema, ipc}.\n"
        "static const char* AGENT_TOOLS_JSON = R\"PMSTOOLS(" + payload + ")PMSTOOLS\";\n"
    )
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != header:
            raise SystemExit(
                f"{OUT.relative_to(ROOT)} is stale — "
                "run: python3 tools/gen_agent_tools.py"
            )
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return

    OUT.write_text(header)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(tools)} tools, {n_ipc} direct-IPC")
    bridged = sorted(t["name"] for t in tools if not t["ipc"])
    print("python-only (served via the server.py bridge):", ", ".join(bridged))


if __name__ == "__main__":
    main()
