#!/usr/bin/env python3
"""Generate src/generated/agent_tools.h for the in-app agent harness.

Sources of truth (see AGENT_HARNESS.md):
  - mcp_server/server.py --dump-tools   → names, descriptions, input schemas
  - src/ipc_server.cpp                  → which methods the socket actually serves

Each tool is tagged "ipc": true when its name is a real IPC method (the
harness dispatches those straight to the editor socket) or "ipc": false when
it is implemented inside server.py (activity scans, contact sheets,
transcript search orchestration, ...) — those route through the harness's
server.py MCP stdio bridge. The flag is computed here so neither side
hand-maintains a list that can rot.

Run from the repo root after changing tool definitions in server.py:
    python3 tools/gen_agent_tools.py
The output header is committed, same policy as the fx_* generated headers.
Pass --check to verify the committed header is fresh without rewriting it
(exit 1 if stale) — for CI or a pre-commit hook.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVER = ROOT / "mcp_server" / "server.py"
IPC = ROOT / "src" / "ipc_server.cpp"
OUT = ROOT / "src" / "generated" / "agent_tools.h"


def main():
    dump = subprocess.run(
        [sys.executable, str(SERVER), "--dump-tools"],
        capture_output=True, text=True,
    )
    if dump.returncode != 0:
        # The MCP server couldn't enumerate its tools (typically the `mcp` package
        # isn't installed in this environment). In --check mode this is a build
        # guard, not the point of the build — skip rather than break a checkout
        # that just wants the editor. A real regen (no --check) still fails loudly.
        if "--check" in sys.argv:
            print("agent_tools.h check skipped — could not run server.py "
                  "--dump-tools (mcp deps missing?)")
            return
        raise SystemExit(f"server.py --dump-tools failed:\n{dump.stderr}")
    tools = json.loads(dump.stdout)

    ipc_src = IPC.read_text()
    methods = set(re.findall(r'method == "([a-zA-Z0-9_]+)"', ipc_src))
    if not methods:
        raise SystemExit("no IPC methods found in ipc_server.cpp — wrong path?")

    # The in-app harness gets the AGENT audience only: operator tools (ui_input,
    # camera/monitor toggles, vrecord, canvas geometry) drive the live UI and are
    # reserved for an external driver, not the autonomous editing agent.
    operator = [t for t in tools if t.get("audience") == "operator"]
    agent_tools = [t for t in tools if t.get("audience") != "operator"]

    for t in agent_tools:
        t["ipc"] = t["name"] in methods

    # Categorized index — a compact navigable map the harness appends to its
    # system prompt so the model can orient across the surface by domain.
    by_cat: dict[str, list[str]] = {}
    for t in agent_tools:
        by_cat.setdefault(t.get("category", "misc"), []).append(t["name"])
    cat_order = ["read", "timeline", "text", "shape", "fx", "audio", "style",
                 "transcript", "export", "project", "capture", "playback", "system", "misc"]
    index_lines = [
        f"{cat}: " + ", ".join(sorted(by_cat[cat]))
        for cat in cat_order if cat in by_cat
    ]
    index_str = "TOOLS BY CATEGORY (call by exact name):\n" + "\n".join(index_lines)

    # Strip metadata the C++ OpenAI decl doesn't need (category/audience).
    slim = [
        {"name": t["name"], "description": t["description"],
         "inputSchema": t["inputSchema"], "ipc": t["ipc"]}
        for t in agent_tools
    ]
    n_ipc = sum(t["ipc"] for t in slim)
    payload = json.dumps(slim, ensure_ascii=False, separators=(",", ":"))
    if ")PMSTOOLS" in payload or ")PMSIDX" in index_str:
        raise SystemExit("raw-string delimiter collision — change the delimiter")

    header = (
        "// generated by tools/gen_agent_tools.py — DO NOT EDIT.\n"
        "// Source of truth: mcp_server/server.py (--dump-tools) intersected with\n"
        "// the IPC methods in src/ipc_server.cpp. Regenerate after changing tool\n"
        "// definitions:  python3 tools/gen_agent_tools.py\n"
        f"// {len(slim)} agent tools ({n_ipc} direct-IPC, {len(slim) - n_ipc} via the\n"
        f"// server.py bridge); {len(operator)} operator-only tools withheld from the\n"
        "// in-app harness ("
        + ", ".join(sorted(t["name"] for t in operator)) + ").\n"
        "#pragma once\n\n"
        "// JSON array of {name, description, inputSchema, ipc}.\n"
        "static const char* AGENT_TOOLS_JSON = R\"PMSTOOLS(" + payload + ")PMSTOOLS\";\n\n"
        "// Categorized name index, appended to the harness system prompt.\n"
        "static const char* AGENT_TOOLS_INDEX = R\"PMSIDX(" + index_str + ")PMSIDX\";\n"
    )
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != header:
            raise SystemExit(
                f"{OUT.relative_to(ROOT)} is stale — "
                "run: python3 tools/gen_agent_tools.py"
            )
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return

    OUT.write_text(header)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(slim)} agent tools, {n_ipc} direct-IPC, "
          f"{len(operator)} operator-only withheld")
    bridged = sorted(t["name"] for t in slim if not t["ipc"])
    print("python-only (served via the server.py bridge):", ", ".join(bridged))


if __name__ == "__main__":
    main()
