#!/usr/bin/env python3
"""Generate src/generated/arkit_face_mesh.h from the canonical ARKit face mesh.

Primary input: Apple's FaceMesh.obj shipped with Xcode:
  /Applications/Xcode.app/Contents/Developer/Library/ARKit/FaceMesh.obj

Fallback input: a .mat file containing 'TriangleIndices' (3x2304, 1-indexed)
from a dumped ARSession (e.g. Jeon-apple_facestim_generation). In this case
UVs are stubbed with zeros and a TODO is emitted.

Semantic landmark correspondence now lives in gen_arkit_mp_map.py
(arkit_mp_map.h), computed from canonical rest-pose meshes.
"""
import os
import sys
import numpy as np

here = os.path.dirname(os.path.abspath(__file__))
out_dir = os.path.join(here, "..", "src", "generated")


def parse_obj(path):
    verts = []
    uvs = []
    vt_raw = []
    tris = []
    v2vt = {}
    with open(path) as f:
        for line in f:
            p = line.split()
            if not p:
                continue
            if p[0] == "v":
                verts.append((float(p[1]), float(p[2]), float(p[3])))
            elif p[0] == "vt":
                vt_raw.append((float(p[1]), float(p[2])))
            elif p[0] == "f":
                vs = []
                for x in p[1:4]:
                    parts = x.split("/")
                    vi = int(parts[0]) - 1
                    ti = int(parts[1]) - 1 if len(parts) > 1 and parts[1] else 0
                    v2vt[vi] = ti
                    vs.append(vi)
                tris.append(vs)
    npts = len(verts)
    ntri = len(tris)
    if not vt_raw:
        uv = [(0.0, 0.0)] * npts
    elif len(vt_raw) == npts:
        uv = vt_raw          # ARKit dumps: vt is 1:1 with v
    else:
        uv = [vt_raw[v2vt[i]] for i in range(npts)]
    return verts, uv, tris


def parse_mat(path):
    try:
        import scipy.io
    except Exception as exc:
        raise RuntimeError("scipy is required to read .mat files") from exc
    m = scipy.io.loadmat(path)
    if "TriangleIndices" not in m:
        raise RuntimeError(".mat file must contain 'TriangleIndices'")
    tri = m["TriangleIndices"].astype(np.int32)  # shape (3, 2304), 1-indexed
    ntri = tri.shape[1]
    npts = int(tri.max())
    tris = []
    for t in range(ntri):
        tris.append([int(tri[0, t] - 1), int(tri[1, t] - 1), int(tri[2, t] - 1)])
    uv = [(0.0, 0.0)] * npts
    return npts, uv, tris


def write_mesh_header(npts, uv, tris, out_path):
    out = []
    out.append("// GENERATED by tools/gen_arkit_mesh.py")
    out.append("// ARKit face mesh: %d vertices, %d triangles." % (npts, len(tris)))
    if all(u == (0.0, 0.0) for u in uv):
        out.append("// k_arkit_uv is stubbed — populate from ARFaceGeometry.textureCoordinates on device.")
    out.append("#pragma once")
    out.append("static const int ARKIT_NPTS = %d;" % npts)
    out.append("static const int ARKIT_NTRI = %d;" % len(tris))
    out.append("static const float k_arkit_uv[%d][2] = {" % npts)
    for u, v in uv:
        out.append("    {%sf, %sf}," % (u, v))
    out.append("};")
    out.append("static const unsigned short k_arkit_tris[%d][3] = {" % len(tris))
    for a, b, c in tris:
        out.append("    {%d, %d, %d}," % (a, b, c))
    out.append("};")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", out_path)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/Applications/Xcode.app/Contents/Developer/Library/ARKit/FaceMesh.obj"
    if src.endswith(".mat"):
        npts, uv, tris = parse_mat(src)
    else:
        _, uv, tris = parse_obj(src)
        npts = len(uv)
    write_mesh_header(npts, uv, tris, os.path.join(out_dir, "arkit_face_mesh.h"))
    # arkit_landmark_map.h is gone: the hand-typed semantic table had L/R
    # inverted and is replaced by the exact offline correspondence from
    # gen_arkit_mp_map.py (arkit_mp_map.h).


if __name__ == "__main__":
    main()
