#!/usr/bin/env python3
"""Generate src/generated/face_mesh_edges.h: MediaPipe face-mesh connection sets
(tesselation, contours = lips/eyes/brows/oval, irises) as [a, b] landmark index
pairs, in MediaPipe's order, for FaceTrack.mesh (docs/SCRIPT_API.md §3.1).

Requires the mediapipe Python package (Apache 2.0):
  python tools/gen_face_mesh_edges.py
"""
from pathlib import Path

from mediapipe.tasks.python import vision

OUT = Path(__file__).resolve().parents[1] / "src" / "generated" / "face_mesh_edges.h"
conn = vision.FaceLandmarksConnections
SETS = {
    "kFaceTesselation": conn.FACE_LANDMARKS_TESSELATION,
    "kFaceContours": conn.FACE_LANDMARKS_CONTOURS,
    "kFaceIrises": list(conn.FACE_LANDMARKS_LEFT_IRIS) + list(conn.FACE_LANDMARKS_RIGHT_IRIS),
}

lines = [
    "// GENERATED by tools/gen_face_mesh_edges.py from mediapipe",
    "// vision.FaceLandmarksConnections (Apache 2.0). Do not edit.",
    "#pragma once",
    "",
]
for name, edges in SETS.items():
    pairs = [f"{{{c.start},{c.end}}}" for c in edges]
    lines.append(f"static const int {name}[{len(pairs)}][2] = {{")
    for i in range(0, len(pairs), 12):
        lines.append("    " + ",".join(pairs[i:i + 12]) + ",")
    lines.append("};")
    lines.append("")
OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({', '.join(f'{k}={len(v)}' for k, v in SETS.items())})")
