#pragma once
// conform.h — DEAD.
//
// The frame-rate conform API (conform_needed / conform_path / conform_start /
// conform_is_ready / conform_status / conform_cancel, ConformState,
// ConformStatus) was removed together with the conform pipeline (see
// conform.cpp). The all-intra H.264 intermediate generated by proxy_start()
// (proxy.h) is the single decode/export source; clip_video_src() returns it
// when proxy_is_ready(), else the original source.
//
// Retained comment-only so the build breaks only via CMakeLists.txt; nothing
// includes or references this header anymore.
