// conform.cpp — DEAD.
//
// The frame-rate conform pipeline (project-fps transcodes with temporal
// blending) has been removed. The all-intra H.264 intermediate generated by
// the proxy pipeline (proxy.h) is now the single decode/export source per
// source file — CFR at min(source fps, 30), rotation baked, no audio — so a
// separate per-clip fps conform is obsolete. clip_video_src() returns the
// intermediate when proxy_is_ready(), else the original source.
//
// Kept as an empty translation unit so the build breaks only when the
// integrator removes it from CMakeLists.txt; every conform_* call site has
// been removed from the tree.
