#pragma once
#include <string>
#include <functional>

std::string hubert_onnx_path();
bool        hubert_onnx_exists();

// Convert source audio using pre-exported ONNX models.
// f0_semitones: manual transpose. f0_auto: probe {-12,0,+12} octave shifts
// against the model (best output pitch tracking wins) and add the winner.
// voice_onnx: per-model ONNX (generated by vc_export.py from the .pth).
// Returns empty string on success, error message on failure.
std::string vc_onnx_convert(
    const std::string& source_wav,
    const std::string& voice_onnx,
    const std::string& output_wav,
    int f0_semitones,
    bool f0_auto,
    std::function<void(float, const std::string&)> on_progress = nullptr);
