# EmbedFile.cmake
# Usage: cmake -DINPUT=<file> -DVAR=<identifier> -DOUTPUT=<header> -P EmbedFile.cmake
#
# Generates a header with:
#   static const unsigned char <VAR>[];
#   static const unsigned int  <VAR>_size;

cmake_minimum_required(VERSION 3.20)

file(READ "${INPUT}" content HEX)
string(LENGTH "${content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

# Build C array body, 16 bytes per line
set(array_body "")
set(line "  ")
set(col 0)
set(i 0)
while(i LESS hex_len)
    string(SUBSTRING "${content}" ${i} 2 byte_hex)
    set(line "${line}0x${byte_hex},")
    math(EXPR col "${col} + 1")
    math(EXPR i   "${i} + 2")
    if(col EQUAL 16)
        set(array_body "${array_body}${line}\n")
        set(line "  ")
        set(col 0)
    endif()
endwhile()
if(NOT col EQUAL 0)
    set(array_body "${array_body}${line}")
endif()

file(WRITE "${OUTPUT}"
"#pragma once
// Auto-generated by cmake/EmbedFile.cmake — do not edit.
static const unsigned int  ${VAR}_size = ${byte_count}u;
static const unsigned char ${VAR}[] = {
${array_body}
};
")

message(STATUS "Embedded ${INPUT} -> ${OUTPUT}  (${byte_count} bytes)")
